url:

  customLabelUrl : http://localhost:20004/mdvn-template/templates/customLabel
  retrieveTagsUrl : http://localhost:20002/mdvn-tag/tags/retrieveBaseInfo
  retrieveMembersUrl : http://localhost:20001/mdvn-staff/staff/retrieveBaseInfo
  retrieveRoleUrl : http://localhost:20004/mdvn-template/templates/retrieveRoleBaseInfo
  retrieveLabelUrl : http://localhost:20004/mdvn-template/templates/retrieveLabel

